apiVersion: v1
kind: Secret
metadata:
  name: discord-bot-secrets
  namespace: dbot-prod
type: Opaque
stringData:
  LLM_KEY: "REPLACE_ME"
  LLM_URL: "REPLACE_ME"
  DISCORD_TOKEN: "REPLACE_ME"
  MODEL_NAME: "REPLACE_ME"
